[env:pro8MHzatmega328]
platform  = atmelavr
board     = pro8MHzatmega328
framework = arduino

upload_port     = COM6
upload_protocol = arduino
upload_speed    = 57600
monitor_speed   = 115200

lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    nrf24/RF24
    rocketscream/Low-Power
